### ISSUE TITLE
10x-RNA-v2 cell barcode sequence is null

### ISSUE THREAD

**Issue by yttria-aniseia** [IGVF/seqspec#1]
the specification for 10x Single Cell RNA 3' v2 appears to contain a mistaken sequence entry for the R1 barcode:
https://github.com/IGVF/seqspec/blob/d77ca7e390f1ae9ebac596bbed4ab0d6526f612a/specs/10x-RNA-v2/spec.yaml#L64
it seems that this should be
```diff
      sequence: NNNNNNNNNNNNNNNN

**Comment by sbooeshaghi** [comment]
You're right! Could you submit a pull request against the `devel` branch making the change?

**Comment by yttria-aniseia** [comment]
this repository doesn't have a `devel` branch like https://github.com/pachterlab/seqspec does, so the PR is against main.

**Comment by sbooeshaghi** [comment]
Oh my apologies- I incorrectly referenced referenced the wrong repository. Thank you for the PR!
