### ISSUE TITLE
read seqspec from URI

### ISSUE THREAD

**Issue by hitz** [IGVF/seqspec#17]
It would be cool if the lib could read seqspec from a URI instead of just a local file path

**Comment by hitz** [comment]
ok I wrote some code to do this but don't want to expand test suite over the internet to use URIs.  @sbooeshaghi how do you run tests locally?

**Comment by detrout** [comment]
You could either use a mocking library 
https://pypi.org/project/requests-mock/

or alternatively launch a local HTTP server instance to host a test seqspec.
https://docs.python.org/3/library/http.server.html
https://pytest-httpserver.readthedocs.io/en/latest/

**Comment by hitz** [comment]
> seqspec print http://myurl.com/customspec.yaml

No, not the seqspec file itself, but rather the the references within it to the fastqs and index files.  Ha, which means I think I modified the wrong function.

**Comment by hitz** [comment]
those should be in dev-requirements.txt right?

**Comment by detrout** [comment]
Yes, the package dependencies are listed in dev-requirements.

**Comment by sbooeshaghi** [comment]
onlists can now be supplied a uri

https://github.com/IGVF/seqspec/commit/242cdf09c58cd8864a3d98f58563910cdc5fe354
