### ISSUE TITLE
DNA for modalities

### ISSUE THREAD

**Issue by visze** [IGVF/seqspec#26]
I try to create a seqspec file for MPRAs. for teh aqssignment sequencing we are sequencing genomic/synthetic regions which we designed and the BC which is associated with. So I would say this is sequencing of a DNA modality. But seqspec allows only this:

`'DNA' is not one of ['rna', 'tag', 'protein', 'atac', 'crispr'] in spec['modalities'][0]`

None of them fits to the modality in our case

**Comment by visze** [comment]
Same for `region_type`. Because not every designed sequence is a "real" genomic sequence `gDNA` I would rather use `DNA` than `gDNA`. but `DNA` is not allowed

**Comment by sbooeshaghi** [comment]
Good idea to have dna as one of the modalities and region_types. Can you put in a pull request to the spec and I can review and accept?

**Comment by sbooeshaghi** [comment]
I've gone ahead and added `dna` to both `region_type` and `modalities` in the most recent commit. 

https://github.com/IGVF/seqspec/commit/5f17ffcfb11aef35d43166f16488164f15f13451
