### ISSUE TITLE
to_dict() should return the order parameter.

### ISSUE THREAD

**Issue by detrout** [IGVF/seqspec#7]
While I was writing about how the jsonschema validator works better with to_dict(), I remembered to check that order is actually being set in the schema files.

I think actually the reason for the order validation errors is .to_dict() probably also needs to return the order property.

```python
@@ -101,6 +99,7 @@ class Region(yaml.YAMLObject):
             "region_type": self.region_type,
             "name": self.name,
             "sequence_type": self.sequence_type,
+            "order": self.order,
             "onlist": self.onlist.to_dict() if self.onlist else None,
             "sequence": self.sequence,
             "min_len": self.min_len,

```

**Comment by detrout** [comment]
After getting the validator working and running it on all of the yaml files in assays there's a reasonable number of spec yamls that manage to load without setting an order argument so the above code fails.

I had to use `"order": getattr(self, "order", None)` to avoid exceptions.

But that leads to the question maybe order should get set in the constructor? or is order even really needed? The regions are loaded from ordered lists, are stored in ordered lists.

There's also the question of if you have an order parameter what happens if the order argument and the order in the file don't match? Currently regions are returned in the order found in the yaml file, should it instead work by returning regions in sorted by the self.order attribute, or is order really needed?

**Comment by sbooeshaghi** [comment]
I think the order argument should be deprecated. Adding as a todo
