### ISSUE TITLE
Sequencing data repositories which accept seqspec?

### ISSUE THREAD

**Issue by photocyte** [IGVF/seqspec#8]
Hi there,

Is there any list of sequencing data repositories which accept seqspec? (realizing that seqspec is very new, and direct support is unlikely at this stage, but maybe there are some best practices even at this point?)

For example, does NCBI SRA accept seqspec?

**Comment by detrout** [comment]
The <a href="https://igvf.org/">IGVF</a> DACC is currently planning on using it as they build a <a href="https://data.igvf.org/">portal</a> for this project.

IGVF is what motivated https://github.com/IGVF/seqspec/pull/2

**Comment by sbooeshaghi** [comment]
Hi @photocyte, this is definitely a goal we are aiming for with `seqspec`. For now, we advise users to generate `seqspec` specification files for their data and make them available (one way is through a PR to this repo (under assays)!).
